

DECL_LOQUATY_FUNC(EntisGLS4_RenderContext_copyBufferFrom);
DECL_LOQUATY_FUNC(EntisGLS4_RenderContext_attachMultiTargetImages);
DECL_LOQUATY_FUNC(EntisGLS4_RenderContext_getMultiTargetImages);
DECL_LOQUATY_FUNC(EntisGLS4_RenderContext_setProjectionScreen);
DECL_LOQUATY_FUNC(EntisGLS4_RenderContext_getProjectionScreen);
DECL_LOQUATY_FUNC(EntisGLS4_RenderContext_setCamera);
DECL_LOQUATY_FUNC(EntisGLS4_RenderContext_setCameraAngleVector);
DECL_LOQUATY_FUNC(EntisGLS4_RenderContext_getCamera);
DECL_LOQUATY_FUNC(EntisGLS4_RenderContext_isSphereIntoView);
DECL_LOQUATY_FUNC(EntisGLS4_RenderContext_setParallax);
DECL_LOQUATY_FUNC(EntisGLS4_RenderContext_getParallax);
DECL_LOQUATY_FUNC(EntisGLS4_RenderContext_setZClipRange);
DECL_LOQUATY_FUNC(EntisGLS4_RenderContext_setLightEntries);
DECL_LOQUATY_FUNC(EntisGLS4_RenderContext_setShadowMap);
DECL_LOQUATY_FUNC(EntisGLS4_RenderContext_setFog);
DECL_LOQUATY_FUNC(EntisGLS4_RenderContext_enableFog);
DECL_LOQUATY_FUNC(EntisGLS4_RenderContext_currentParallaxView);
DECL_LOQUATY_FUNC(EntisGLS4_RenderContext_selectParallaxView);
DECL_LOQUATY_FUNC(EntisGLS4_RenderContext_begin3DRenderer);
DECL_LOQUATY_FUNC(EntisGLS4_RenderContext_end3DRenderer);
DECL_LOQUATY_FUNC(EntisGLS4_RenderContext_getRenderDeviceObject);


