

DECL_LOQUATY_FUNC(EntisGLS4_Window_createDisplay);
DECL_LOQUATY_FUNC(EntisGLS4_Window_closeDisplay);
DECL_LOQUATY_FUNC(EntisGLS4_Window_getOptionalFlags);
DECL_LOQUATY_FUNC(EntisGLS4_Window_setOptionalFlags);
DECL_LOQUATY_FUNC(EntisGLS4_Window_changeCooperationLevel);
DECL_LOQUATY_FUNC(EntisGLS4_Window_getCooperationLevel);
DECL_LOQUATY_FUNC(EntisGLS4_Window_changeDisplaySize);
DECL_LOQUATY_FUNC(EntisGLS4_Window_getDisplaySize);
DECL_LOQUATY_FUNC(EntisGLS4_Window_enableChangePhysicalMode);
DECL_LOQUATY_FUNC(EntisGLS4_Window_enableZBuffer);
DECL_LOQUATY_FUNC(EntisGLS4_Window_setStereoDisplayMode);
DECL_LOQUATY_FUNC(EntisGLS4_Window_isSupportedStereoDisplayMode);
DECL_LOQUATY_FUNC(EntisGLS4_Window_initWindowPosition);
DECL_LOQUATY_FUNC(EntisGLS4_Window_getNormalWindowPosition);
DECL_LOQUATY_FUNC(EntisGLS4_Window_getInternalDisplayPosition);
DECL_LOQUATY_FUNC(EntisGLS4_Window_setExteriorBackgroundFrame);
DECL_LOQUATY_FUNC(EntisGLS4_Window_postUpdate);
DECL_LOQUATY_FUNC(EntisGLS4_Window_postUIThread);
DECL_LOQUATY_FUNC(EntisGLS4_Window_isWindowActive);
DECL_LOQUATY_FUNC(EntisGLS4_Window_setWindowCaption);
DECL_LOQUATY_FUNC(EntisGLS4_Window_showCursor);
DECL_LOQUATY_FUNC(EntisGLS4_Window_isShowCursor);
DECL_LOQUATY_FUNC(EntisGLS4_Window_setCursor);
DECL_LOQUATY_FUNC(EntisGLS4_Window_moveCursorPosition);
DECL_LOQUATY_FUNC(EntisGLS4_Window_getCursorPosition);
DECL_LOQUATY_FUNC(EntisGLS4_Window_getMonitorFrequency);
DECL_LOQUATY_FUNC(EntisGLS4_Window_getRenderDevice);
DECL_LOQUATY_FUNC(EntisGLS4_Window_lock);
DECL_LOQUATY_FUNC(EntisGLS4_Window_unlock);


