

DECL_LOQUATY_FUNC(EntisGLS4_SceneComposition_applySceneParameters);
DECL_LOQUATY_FUNC(EntisGLS4_SceneComposition_prepareToRender);
DECL_LOQUATY_FUNC(EntisGLS4_SceneComposition_initializeItems);
DECL_LOQUATY_FUNC(EntisGLS4_SceneComposition_playComposition);
DECL_LOQUATY_FUNC(EntisGLS4_SceneComposition_stopCompositoin);
DECL_LOQUATY_FUNC(EntisGLS4_SceneComposition_restartComposition);
DECL_LOQUATY_FUNC(EntisGLS4_SceneComposition_pauseCompositoin);
DECL_LOQUATY_FUNC(EntisGLS4_SceneComposition_finishComposition);
DECL_LOQUATY_FUNC(EntisGLS4_SceneComposition_isPlayingComposition);
DECL_LOQUATY_FUNC(EntisGLS4_SceneComposition_isPausedComposition);
DECL_LOQUATY_FUNC(EntisGLS4_SceneComposition_isCompositionFinished);
DECL_LOQUATY_FUNC(EntisGLS4_SceneComposition_getCurrentPlayingFrame);
DECL_LOQUATY_FUNC(EntisGLS4_SceneComposition_postTimelineFrame);
DECL_LOQUATY_FUNC(EntisGLS4_SceneComposition_removeSpaceChild);
DECL_LOQUATY_FUNC(EntisGLS4_SceneComposition_postDelayRemoveItem);
DECL_LOQUATY_FUNC(EntisGLS4_SceneComposition_getUserObject);
DECL_LOQUATY_FUNC(EntisGLS4_SceneComposition_setUserObject);
DECL_LOQUATY_FUNC(EntisGLS4_SceneComposition_isEditMode);


