

DECL_LOQUATY_CONSTRUCTOR(EntisGLS4_ImageComposition_Layer);
DECL_LOQUATY_CONSTRUCTOR_N(EntisGLS4_ImageComposition_Layer,1);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_Layer_getTotalLayerCount);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_Layer_getLayerName);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_Layer_setLayerName);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_Layer_getLayerType);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_Layer_setLayerType);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_Layer_getLayerPosition);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_Layer_setLayerPosition);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_Layer_getLayerBlendMode);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_Layer_setLayerBlendMode);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_Layer_isLayerVisible);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_Layer_setLayerVisible);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_Layer_getLayerTransparency);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_Layer_setLayerTransparency);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_Layer_getSubLayerCount);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_Layer_getSubLayerAt);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_Layer_layerSizeOf);


