

DECL_LOQUATY_CONSTRUCTOR(EntisGLS4_SceneLight);
DECL_LOQUATY_FUNC(EntisGLS4_SceneLight_getLightType);
DECL_LOQUATY_FUNC(EntisGLS4_SceneLight_setLightType);
DECL_LOQUATY_FUNC(EntisGLS4_SceneLight_getLightColor);
DECL_LOQUATY_FUNC(EntisGLS4_SceneLight_setLightColor);
DECL_LOQUATY_FUNC(EntisGLS4_SceneLight_getLightBrightness);
DECL_LOQUATY_FUNC(EntisGLS4_SceneLight_setLightBrightness);
DECL_LOQUATY_FUNC(EntisGLS4_SceneLight_getAttenuationPower);
DECL_LOQUATY_FUNC(EntisGLS4_SceneLight_setAttenuationPower);
DECL_LOQUATY_FUNC(EntisGLS4_SceneLight_getLightPosition);
DECL_LOQUATY_FUNC(EntisGLS4_SceneLight_setLightPosition);
DECL_LOQUATY_FUNC(EntisGLS4_SceneLight_getLightDirection);
DECL_LOQUATY_FUNC(EntisGLS4_SceneLight_setLightDirection);
DECL_LOQUATY_FUNC(EntisGLS4_SceneLight_getLightAngle);
DECL_LOQUATY_FUNC(EntisGLS4_SceneLight_setLightAngle);
DECL_LOQUATY_FUNC(EntisGLS4_SceneLight_getLightGradation);
DECL_LOQUATY_FUNC(EntisGLS4_SceneLight_setLightGradation);
DECL_LOQUATY_FUNC(EntisGLS4_SceneLight_IsEnabledShadowMapping);
DECL_LOQUATY_FUNC(EntisGLS4_SceneLight_enableShadowMapping);
DECL_LOQUATY_FUNC(EntisGLS4_SceneLight_getShadowMappingParam);
DECL_LOQUATY_FUNC(EntisGLS4_SceneLight_setShadowMappingParam);


