

DECL_LOQUATY_CONSTRUCTOR(EntisGLS4_ModelBuffer);
DECL_LOQUATY_FUNC(EntisGLS4_ModelBuffer_loadModel);
DECL_LOQUATY_FUNC(EntisGLS4_ModelBuffer_readModel);
DECL_LOQUATY_FUNC(EntisGLS4_ModelBuffer_saveModel);
DECL_LOQUATY_FUNC(EntisGLS4_ModelBuffer_writeModel);
DECL_LOQUATY_FUNC(EntisGLS4_ModelBuffer_getTextureLibrary);
DECL_LOQUATY_FUNC(EntisGLS4_ModelBuffer_getMaterialLibrary);
DECL_LOQUATY_FUNC(EntisGLS4_ModelBuffer_getPoseLibrary);
DECL_LOQUATY_FUNC(EntisGLS4_ModelBuffer_getBoneAs);
DECL_LOQUATY_FUNC(EntisGLS4_ModelBuffer_getBoneIdentityOf);
DECL_LOQUATY_FUNC(EntisGLS4_ModelBuffer_getMarkerCount);
DECL_LOQUATY_FUNC(EntisGLS4_ModelBuffer_getMarkerIdentityAt);
DECL_LOQUATY_FUNC(EntisGLS4_ModelBuffer_getMarkerAt);
DECL_LOQUATY_FUNC(EntisGLS4_ModelBuffer_getMarkerAs);
DECL_LOQUATY_FUNC(EntisGLS4_ModelBuffer_calcMarkerMatrix);


