

DECL_LOQUATY_CONSTRUCTOR(EntisGLS4_Material);
DECL_LOQUATY_FUNC(EntisGLS4_Material_faceAttr);
DECL_LOQUATY_FUNC(EntisGLS4_Material_backAttr);
DECL_LOQUATY_FUNC(EntisGLS4_Material_isEnabledBackAttr);
DECL_LOQUATY_FUNC(EntisGLS4_Material_enableBackAttr);
DECL_LOQUATY_FUNC(EntisGLS4_Material_getTexture);
DECL_LOQUATY_FUNC(EntisGLS4_Material_getBackTexture);
DECL_LOQUATY_FUNC(EntisGLS4_Material_getTextureType);
DECL_LOQUATY_FUNC(EntisGLS4_Material_getBackTextureType);
DECL_LOQUATY_FUNC(EntisGLS4_Material_getTextureApply);
DECL_LOQUATY_FUNC(EntisGLS4_Material_getBackTextureApply);
DECL_LOQUATY_FUNC(EntisGLS4_Material_getTextureParam);
DECL_LOQUATY_FUNC(EntisGLS4_Material_getBackTextureParam);
DECL_LOQUATY_FUNC(EntisGLS4_Material_findTextureTypeOf);
DECL_LOQUATY_FUNC(EntisGLS4_Material_findBackTextureTypeOf);
DECL_LOQUATY_FUNC(EntisGLS4_Material_setTexture);
DECL_LOQUATY_FUNC(EntisGLS4_Material_setBackTexture);
DECL_LOQUATY_FUNC(EntisGLS4_Material_updateBuffer);


