#!/usr/bin/env python3
"""Prepare a read-only SDK's SSystem synchronism source for the SDL backend."""

# Support direct execution from any working directory.
import sys as _sys
from pathlib import Path as _BootstrapPath
_sys.path.insert(0, str(next(parent / "tools" for parent in _BootstrapPath(__file__).resolve().parents
                             if (parent / "tools" / "_bootstrap.py").is_file())))
from _bootstrap import ROOT

import argparse
from pathlib import Path
import re


def prepare(source: Path, output: Path) -> None:
    text = source.read_text(encoding="utf-8-sig")
    start = text.index("#if\tdefined(__PLATFORM_UNIX_LIKE__)")
    end = text.index("using namespace SSystem ;", start)
    platform_header = text[start:end]
    if not all(token in platform_header for token in
               ("#include <linux/futex.h>", "#include <sys/syscall.h>",
                "return\tsyscall( __NR_futex", "atomic_int_t __atomic_swap")):
        raise ValueError("SDK synchronism platform preamble changed; review required")
    replacement = '''#include "platform/sdl/synchronization.h"

static_assert(sizeof(atomic_int_t) == sizeof(int), "SSystem requires 32-bit futex words");

atomic_int_t __atomic_swap( atomic_int_t n, volatile atomic_int_t * p )
{
    return __atomic_exchange_n( p, n, __ATOMIC_SEQ_CST );
}

'''
    text = text[:start] + replacement + text[end:]
    # The only window reference is in a disabled/commented Windows paint loop.
    # Avoid pulling the Android EGL window producer into a synchronization TU.
    for unused in ("#include <sakuragl/sgl_window.h>", "using namespace SakuraGL ;"):
        if text.count(unused) != 1:
            raise ValueError(f"SDK synchronism dependency changed: {unused}")
        text = text.replace(unused, "")
    text, count = re.subn(r"\bfutex\s*\(", "study::platform::sdl::Futex(", text)
    if count != 10:
        raise ValueError(f"Expected 10 reviewed futex calls, found {count}")
    operations = set(re.findall(r"\bFUTEX_[A-Z_]+\b", text))
    if operations != {"FUTEX_WAIT", "FUTEX_WAKE"}:
        raise ValueError(f"Unsupported futex operations in SDK: {operations}")
    text = text.replace("FUTEX_WAIT", "study::platform::sdl::FutexWait")
    text = text.replace("FUTEX_WAKE", "study::platform::sdl::FutexWake")
    text, count = re.subn(r"\bgettid\s*\(\s*\)", "study::platform::sdl::CurrentThreadId()", text)
    if count != 12:
        raise ValueError(f"Expected 12 reviewed thread-ID references, found {count}")
    if source.resolve() == output.resolve():
        raise ValueError("Refusing to overwrite the SDK source")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("// Generated by tools/sdk/prepare_sdl_sync.py; edit the project adapter.\n#include <cstdarg>\n" + text,
                      encoding="utf-8")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    prepare(args.source, args.output)
