

DECL_LOQUATY_FUNC(EntisGLS4_SceneSequencer_getInterpolateMethod);
DECL_LOQUATY_FUNC(EntisGLS4_SceneSequencer_getKeyFrameRange);
DECL_LOQUATY_FUNC(EntisGLS4_SceneSequencer_getKeyFrameParameter);
DECL_LOQUATY_FUNC(EntisGLS4_SceneSequencer_setKeyFrameParameter);
DECL_LOQUATY_FUNC(EntisGLS4_SceneSequencer_getKeyFrameCount);
DECL_LOQUATY_FUNC(EntisGLS4_SceneSequencer_insertKeyFrame);
DECL_LOQUATY_FUNC(EntisGLS4_SceneSequencer_removeKeyFrame);
DECL_LOQUATY_FUNC(EntisGLS4_SceneSequencer_updateAllFrameValues);
DECL_LOQUATY_FUNC(EntisGLS4_SceneSequencer_normalizeKeyFrameOrder);
DECL_LOQUATY_FUNC(EntisGLS4_SceneSequencer_swapKeyFrame);
DECL_LOQUATY_FUNC(EntisGLS4_SceneSequencer_orderKeyFrameIndex);
DECL_LOQUATY_FUNC(EntisGLS4_SceneSequencer_findKeyFrame);
DECL_LOQUATY_FUNC(EntisGLS4_SceneSequencer_getKeyFrameProgress);
DECL_LOQUATY_FUNC(EntisGLS4_SceneSequencer_getFrameMatrix);
DECL_LOQUATY_FUNC(EntisGLS4_SceneSequencer_getFrameVector);
DECL_LOQUATY_FUNC(EntisGLS4_SceneSequencer_getFrameScalar);
DECL_LOQUATY_FUNC(EntisGLS4_SceneSequencer_getFrameInteger);
DECL_LOQUATY_FUNC(EntisGLS4_SceneSequencer_getFrameBoolean);
DECL_LOQUATY_FUNC(EntisGLS4_SceneSequencer_getFrameCommand);


