

DECL_LOQUATY_CONSTRUCTOR(EntisGLS4_TextureLibrary);
DECL_LOQUATY_FUNC(EntisGLS4_TextureLibrary_getTextureAs);
DECL_LOQUATY_FUNC(EntisGLS4_TextureLibrary_addTextureAs);
DECL_LOQUATY_FUNC(EntisGLS4_TextureLibrary_removeTextureAs);
DECL_LOQUATY_FUNC(EntisGLS4_TextureLibrary_removeAllTextures);
DECL_LOQUATY_FUNC(EntisGLS4_TextureLibrary_findTexture);
DECL_LOQUATY_FUNC(EntisGLS4_TextureLibrary_getTextureCount);
DECL_LOQUATY_FUNC(EntisGLS4_TextureLibrary_getTextureIdentityAt);
DECL_LOQUATY_FUNC(EntisGLS4_TextureLibrary_getTextureIdentityOf);
DECL_LOQUATY_FUNC(EntisGLS4_TextureLibrary_getTextureAt);
DECL_LOQUATY_FUNC(EntisGLS4_TextureLibrary_setParentLibrary);
DECL_LOQUATY_FUNC(EntisGLS4_TextureLibrary_addReferenceLibrary);
DECL_LOQUATY_FUNC(EntisGLS4_TextureLibrary_getParentLibrary);
DECL_LOQUATY_FUNC(EntisGLS4_TextureLibrary_getReferenceLibraryCount);
DECL_LOQUATY_FUNC(EntisGLS4_TextureLibrary_getReferenceLibraryAt);
DECL_LOQUATY_FUNC(EntisGLS4_TextureLibrary_detachReferenceLibraryAt);
DECL_LOQUATY_FUNC(EntisGLS4_TextureLibrary_detachReferenceLibraryOf);
DECL_LOQUATY_FUNC(EntisGLS4_TextureLibrary_detachAllReferenceLibraries);
DECL_LOQUATY_FUNC(EntisGLS4_TextureLibrary_commitToDevice);
DECL_LOQUATY_FUNC(EntisGLS4_TextureLibrary_releaseAllDeviceResources);


