

DECL_LOQUATY_CONSTRUCTOR(EntisGLS4_VirtualInput);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_attachPostListenerToWindow);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_detachPostListenerToWindow);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_getJoyStickDeviceMask);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_getBehaviorFlags);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_setBehaviorFlags);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_getAnalogJoyPosition);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_getJoyStickState);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_isJoyButtonPushing);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_getJoyButtonPushed);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_resetJoyButtonPushed);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_resetAllJoyButtonPushed);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_pressInputEvent);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_releaseInputEvent);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_setSoftwareAnalogPosition);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_getInputEvent);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_setInputQueueLimit);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_flushInputQueue);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_addCommand);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_getCommand);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_flushCommandQueue);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_loadFilter);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_addFilter);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_removeFilter);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_removeAllFilter);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_addInputMap);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_removeInputMap);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_removeAllInputMap);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_lock);
DECL_LOQUATY_FUNC(EntisGLS4_VirtualInput_unlock);


