

DECL_LOQUATY_CONSTRUCTOR(EntisGLS4_PaintContext);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_getTargetImage);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_getTargetZBuffer);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_getViewPort);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_attachTargetImage);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_detachTargetImage);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_appendTransformation);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_setTransformation);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_currentAffine);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_currentTransparency);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_pushTransformation);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_popTransformation);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_resetTransformation);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_setPaintFlags);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_getPaintFlags);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_fillClearTarget);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_fillRectangle);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_fillPolygon);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_drawImage);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_drawMesh);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_flush);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_finish);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_drawPoints);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_drawThinLine);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_drawThinLines);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_drawEllipse);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_drawArc);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_drawBezier);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_fillEllipse);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_fillArc);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_freeGradation);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_setLinearGradation);
DECL_LOQUATY_FUNC(EntisGLS4_PaintContext_setRingedGradation);


