

DECL_LOQUATY_FUNC(EntisGLS4_Scene_getProjection);
DECL_LOQUATY_FUNC(EntisGLS4_Scene_setProjection);
DECL_LOQUATY_FUNC(EntisGLS4_Scene_setParallax);
DECL_LOQUATY_FUNC(EntisGLS4_Scene_getParallax);
DECL_LOQUATY_FUNC(EntisGLS4_Scene_setParallaxParam);
DECL_LOQUATY_FUNC(EntisGLS4_Scene_getParallaxParam);
DECL_LOQUATY_FUNC(EntisGLS4_Scene_getShadingMethod);
DECL_LOQUATY_FUNC(EntisGLS4_Scene_setShadingMethod);
DECL_LOQUATY_FUNC(EntisGLS4_Scene_getBackColor);
DECL_LOQUATY_FUNC(EntisGLS4_Scene_setBackColor);
DECL_LOQUATY_FUNC(EntisGLS4_Scene_getVisibleNearDistance);
DECL_LOQUATY_FUNC(EntisGLS4_Scene_getVisibleFarDistance);
DECL_LOQUATY_FUNC(EntisGLS4_Scene_setVisibleDistance);
DECL_LOQUATY_FUNC(EntisGLS4_Scene_getGlobalFog);
DECL_LOQUATY_FUNC(EntisGLS4_Scene_setGlobalFog);
DECL_LOQUATY_FUNC(EntisGLS4_Scene_enableGlobalFog);
DECL_LOQUATY_FUNC(EntisGLS4_Scene_addSceneItem);
DECL_LOQUATY_FUNC(EntisGLS4_Scene_detachSceneItem);
DECL_LOQUATY_FUNC(EntisGLS4_Scene_setMainCamera);
DECL_LOQUATY_FUNC(EntisGLS4_Scene_getMainCamera);
DECL_LOQUATY_FUNC(EntisGLS4_Scene_getCurrentRenderingStage);
DECL_LOQUATY_FUNC(EntisGLS4_Scene_getCurrentRenderingPhase);
DECL_LOQUATY_FUNC(EntisGLS4_Scene_postSceneUpdate);


