/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_entis_android_entisgls4_EntisServiceBootReceiver */

#ifndef _Included_com_entis_android_entisgls4_EntisServiceBootReceiver
#define _Included_com_entis_android_entisgls4_EntisServiceBootReceiver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_entis_android_entisgls4_EntisServiceBootReceiver
 * Method:    onNativeDeviceBoot
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_entis_android_entisgls4_EntisServiceBootReceiver_onNativeDeviceBoot
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
