/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_entis_android_entisgls4_NativeSoundPlayerListener */

#ifndef _Included_com_entis_android_entisgls4_NativeSoundPlayerListener
#define _Included_com_entis_android_entisgls4_NativeSoundPlayerListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_entis_android_entisgls4_NativeSoundPlayerListener
 * Method:    nativeOnStream
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_entis_android_entisgls4_NativeSoundPlayerListener_nativeOnStream
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
