/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_entis_android_entisgls4_UICustomDialog */

#ifndef _Included_com_entis_android_entisgls4_UICustomDialog
#define _Included_com_entis_android_entisgls4_UICustomDialog
#ifdef __cplusplus
extern "C" {
#endif
#undef com_entis_android_entisgls4_UICustomDialog_resultOk
#define com_entis_android_entisgls4_UICustomDialog_resultOk 0L
#undef com_entis_android_entisgls4_UICustomDialog_resultCancel
#define com_entis_android_entisgls4_UICustomDialog_resultCancel 1L
#undef com_entis_android_entisgls4_UICustomDialog_resultYes
#define com_entis_android_entisgls4_UICustomDialog_resultYes 2L
#undef com_entis_android_entisgls4_UICustomDialog_resultNo
#define com_entis_android_entisgls4_UICustomDialog_resultNo 3L
#undef com_entis_android_entisgls4_UICustomDialog_resultRetry
#define com_entis_android_entisgls4_UICustomDialog_resultRetry 4L
#undef com_entis_android_entisgls4_UICustomDialog_resultAbort
#define com_entis_android_entisgls4_UICustomDialog_resultAbort 5L
#undef com_entis_android_entisgls4_UICustomDialog_resultIgnore
#define com_entis_android_entisgls4_UICustomDialog_resultIgnore 6L
#undef com_entis_android_entisgls4_UICustomDialog_resultUser
#define com_entis_android_entisgls4_UICustomDialog_resultUser 7L
/*
 * Class:     com_entis_android_entisgls4_UICustomDialog
 * Method:    callbackItem
 * Signature: (Lcom/entis/android/entisgls4/UICustomDialogInterface/Item;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_entis_android_entisgls4_UICustomDialog_callbackItem
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_entis_android_entisgls4_UICustomDialog_ItemSeekListener */

#ifndef _Included_com_entis_android_entisgls4_UICustomDialog_ItemSeekListener
#define _Included_com_entis_android_entisgls4_UICustomDialog_ItemSeekListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_entis_android_entisgls4_UICustomDialog_ItemClickListener */

#ifndef _Included_com_entis_android_entisgls4_UICustomDialog_ItemClickListener
#define _Included_com_entis_android_entisgls4_UICustomDialog_ItemClickListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_entis_android_entisgls4_UICustomDialog_ItemFocusChangeListener */

#ifndef _Included_com_entis_android_entisgls4_UICustomDialog_ItemFocusChangeListener
#define _Included_com_entis_android_entisgls4_UICustomDialog_ItemFocusChangeListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
