/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_entis_android_entisgls4_VirtualWindow */

#ifndef _Included_com_entis_android_entisgls4_VirtualWindow
#define _Included_com_entis_android_entisgls4_VirtualWindow
#ifdef __cplusplus
extern "C" {
#endif
#undef com_entis_android_entisgls4_VirtualWindow_SYS_EVENT_PAUSE
#define com_entis_android_entisgls4_VirtualWindow_SYS_EVENT_PAUSE 1L
#undef com_entis_android_entisgls4_VirtualWindow_SYS_EVENT_RESUME
#define com_entis_android_entisgls4_VirtualWindow_SYS_EVENT_RESUME 2L
#undef com_entis_android_entisgls4_VirtualWindow_SYS_EVENT_DESTROY
#define com_entis_android_entisgls4_VirtualWindow_SYS_EVENT_DESTROY 3L
/*
 * Class:     com_entis_android_entisgls4_VirtualWindow
 * Method:    onSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_entis_android_entisgls4_VirtualWindow_onSurfaceChanged
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_entis_android_entisgls4_VirtualWindow
 * Method:    draw
 * Signature: (Ljavax/microedition/khronos/opengles/GL10;)V
 */
JNIEXPORT void JNICALL Java_com_entis_android_entisgls4_VirtualWindow_draw
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_entis_android_entisgls4_VirtualWindow
 * Method:    onTouchedDown
 * Signature: (DDI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_entis_android_entisgls4_VirtualWindow_onTouchedDown
  (JNIEnv *, jobject, jdouble, jdouble, jint);

/*
 * Class:     com_entis_android_entisgls4_VirtualWindow
 * Method:    onTouchedUp
 * Signature: (DDI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_entis_android_entisgls4_VirtualWindow_onTouchedUp
  (JNIEnv *, jobject, jdouble, jdouble, jint);

/*
 * Class:     com_entis_android_entisgls4_VirtualWindow
 * Method:    onTouchMoved
 * Signature: (DDI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_entis_android_entisgls4_VirtualWindow_onTouchMoved
  (JNIEnv *, jobject, jdouble, jdouble, jint);

/*
 * Class:     com_entis_android_entisgls4_VirtualWindow
 * Method:    onKeyDown
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_entis_android_entisgls4_VirtualWindow_onKeyDown
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_entis_android_entisgls4_VirtualWindow
 * Method:    onKeyUp
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_entis_android_entisgls4_VirtualWindow_onKeyUp
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_entis_android_entisgls4_VirtualWindow
 * Method:    onChar
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_entis_android_entisgls4_VirtualWindow_onChar
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_entis_android_entisgls4_VirtualWindow
 * Method:    onJoystickAxis
 * Signature: (FFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_entis_android_entisgls4_VirtualWindow_onJoystickAxis
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_entis_android_entisgls4_VirtualWindow
 * Method:    onTimer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_entis_android_entisgls4_VirtualWindow_onTimer
  (JNIEnv *, jobject);

/*
 * Class:     com_entis_android_entisgls4_VirtualWindow
 * Method:    onSystemEvent
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_entis_android_entisgls4_VirtualWindow_onSystemEvent
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_entis_android_entisgls4_VirtualWindow
 * Method:    onMenuCommand
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_entis_android_entisgls4_VirtualWindow_onMenuCommand
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
