/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_entis_android_entisgls4_EntisGLActivity */

#ifndef _Included_com_entis_android_entisgls4_EntisGLActivity
#define _Included_com_entis_android_entisgls4_EntisGLActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_entis_android_entisgls4_EntisGLActivity_MODE_PRIVATE
#define com_entis_android_entisgls4_EntisGLActivity_MODE_PRIVATE 0L
#undef com_entis_android_entisgls4_EntisGLActivity_MODE_WORLD_READABLE
#define com_entis_android_entisgls4_EntisGLActivity_MODE_WORLD_READABLE 1L
#undef com_entis_android_entisgls4_EntisGLActivity_MODE_WORLD_WRITEABLE
#define com_entis_android_entisgls4_EntisGLActivity_MODE_WORLD_WRITEABLE 2L
#undef com_entis_android_entisgls4_EntisGLActivity_MODE_APPEND
#define com_entis_android_entisgls4_EntisGLActivity_MODE_APPEND 32768L
#undef com_entis_android_entisgls4_EntisGLActivity_BIND_AUTO_CREATE
#define com_entis_android_entisgls4_EntisGLActivity_BIND_AUTO_CREATE 1L
#undef com_entis_android_entisgls4_EntisGLActivity_BIND_DEBUG_UNBIND
#define com_entis_android_entisgls4_EntisGLActivity_BIND_DEBUG_UNBIND 2L
#undef com_entis_android_entisgls4_EntisGLActivity_BIND_NOT_FOREGROUND
#define com_entis_android_entisgls4_EntisGLActivity_BIND_NOT_FOREGROUND 4L
#undef com_entis_android_entisgls4_EntisGLActivity_CONTEXT_INCLUDE_CODE
#define com_entis_android_entisgls4_EntisGLActivity_CONTEXT_INCLUDE_CODE 1L
#undef com_entis_android_entisgls4_EntisGLActivity_CONTEXT_IGNORE_SECURITY
#define com_entis_android_entisgls4_EntisGLActivity_CONTEXT_IGNORE_SECURITY 2L
#undef com_entis_android_entisgls4_EntisGLActivity_CONTEXT_RESTRICTED
#define com_entis_android_entisgls4_EntisGLActivity_CONTEXT_RESTRICTED 4L
#undef com_entis_android_entisgls4_EntisGLActivity_RESULT_CANCELED
#define com_entis_android_entisgls4_EntisGLActivity_RESULT_CANCELED 0L
#undef com_entis_android_entisgls4_EntisGLActivity_RESULT_OK
#define com_entis_android_entisgls4_EntisGLActivity_RESULT_OK -1L
#undef com_entis_android_entisgls4_EntisGLActivity_RESULT_FIRST_USER
#define com_entis_android_entisgls4_EntisGLActivity_RESULT_FIRST_USER 1L
#undef com_entis_android_entisgls4_EntisGLActivity_DEFAULT_KEYS_DISABLE
#define com_entis_android_entisgls4_EntisGLActivity_DEFAULT_KEYS_DISABLE 0L
#undef com_entis_android_entisgls4_EntisGLActivity_DEFAULT_KEYS_DIALER
#define com_entis_android_entisgls4_EntisGLActivity_DEFAULT_KEYS_DIALER 1L
#undef com_entis_android_entisgls4_EntisGLActivity_DEFAULT_KEYS_SHORTCUT
#define com_entis_android_entisgls4_EntisGLActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef com_entis_android_entisgls4_EntisGLActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define com_entis_android_entisgls4_EntisGLActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef com_entis_android_entisgls4_EntisGLActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define com_entis_android_entisgls4_EntisGLActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
/*
 * Class:     com_entis_android_entisgls4_EntisGLActivity
 * Method:    nativeMain
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_entis_android_entisgls4_EntisGLActivity_nativeMain
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_entis_android_entisgls4_EntisGLActivity
 * Method:    nativeAbort
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_entis_android_entisgls4_EntisGLActivity_nativeAbort
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_entis_android_entisgls4_EntisGLActivity_ViewTimerRunnable */

#ifndef _Included_com_entis_android_entisgls4_EntisGLActivity_ViewTimerRunnable
#define _Included_com_entis_android_entisgls4_EntisGLActivity_ViewTimerRunnable
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
