/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_entis_android_entisgls4_EntisService */

#ifndef _Included_com_entis_android_entisgls4_EntisService
#define _Included_com_entis_android_entisgls4_EntisService
#ifdef __cplusplus
extern "C" {
#endif
#undef com_entis_android_entisgls4_EntisService_MODE_PRIVATE
#define com_entis_android_entisgls4_EntisService_MODE_PRIVATE 0L
#undef com_entis_android_entisgls4_EntisService_MODE_WORLD_READABLE
#define com_entis_android_entisgls4_EntisService_MODE_WORLD_READABLE 1L
#undef com_entis_android_entisgls4_EntisService_MODE_WORLD_WRITEABLE
#define com_entis_android_entisgls4_EntisService_MODE_WORLD_WRITEABLE 2L
#undef com_entis_android_entisgls4_EntisService_MODE_APPEND
#define com_entis_android_entisgls4_EntisService_MODE_APPEND 32768L
#undef com_entis_android_entisgls4_EntisService_BIND_AUTO_CREATE
#define com_entis_android_entisgls4_EntisService_BIND_AUTO_CREATE 1L
#undef com_entis_android_entisgls4_EntisService_BIND_DEBUG_UNBIND
#define com_entis_android_entisgls4_EntisService_BIND_DEBUG_UNBIND 2L
#undef com_entis_android_entisgls4_EntisService_BIND_NOT_FOREGROUND
#define com_entis_android_entisgls4_EntisService_BIND_NOT_FOREGROUND 4L
#undef com_entis_android_entisgls4_EntisService_CONTEXT_INCLUDE_CODE
#define com_entis_android_entisgls4_EntisService_CONTEXT_INCLUDE_CODE 1L
#undef com_entis_android_entisgls4_EntisService_CONTEXT_IGNORE_SECURITY
#define com_entis_android_entisgls4_EntisService_CONTEXT_IGNORE_SECURITY 2L
#undef com_entis_android_entisgls4_EntisService_CONTEXT_RESTRICTED
#define com_entis_android_entisgls4_EntisService_CONTEXT_RESTRICTED 4L
#undef com_entis_android_entisgls4_EntisService_START_CONTINUATION_MASK
#define com_entis_android_entisgls4_EntisService_START_CONTINUATION_MASK 15L
#undef com_entis_android_entisgls4_EntisService_START_STICKY_COMPATIBILITY
#define com_entis_android_entisgls4_EntisService_START_STICKY_COMPATIBILITY 0L
#undef com_entis_android_entisgls4_EntisService_START_STICKY
#define com_entis_android_entisgls4_EntisService_START_STICKY 1L
#undef com_entis_android_entisgls4_EntisService_START_NOT_STICKY
#define com_entis_android_entisgls4_EntisService_START_NOT_STICKY 2L
#undef com_entis_android_entisgls4_EntisService_START_REDELIVER_INTENT
#define com_entis_android_entisgls4_EntisService_START_REDELIVER_INTENT 3L
#undef com_entis_android_entisgls4_EntisService_START_FLAG_REDELIVERY
#define com_entis_android_entisgls4_EntisService_START_FLAG_REDELIVERY 1L
#undef com_entis_android_entisgls4_EntisService_START_FLAG_RETRY
#define com_entis_android_entisgls4_EntisService_START_FLAG_RETRY 2L
/*
 * Class:     com_entis_android_entisgls4_EntisService
 * Method:    onNativeServiceCreate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_entis_android_entisgls4_EntisService_onNativeServiceCreate
  (JNIEnv *, jobject);

/*
 * Class:     com_entis_android_entisgls4_EntisService
 * Method:    onNativeServiceDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_entis_android_entisgls4_EntisService_onNativeServiceDestroy
  (JNIEnv *, jobject);

/*
 * Class:     com_entis_android_entisgls4_EntisService
 * Method:    onNativeServiceStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_entis_android_entisgls4_EntisService_onNativeServiceStart
  (JNIEnv *, jobject);

/*
 * Class:     com_entis_android_entisgls4_EntisService
 * Method:    onNativeServiceAction
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_entis_android_entisgls4_EntisService_onNativeServiceAction
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
