/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_entis_android_entisgls4_NativeRunnable */

#ifndef _Included_com_entis_android_entisgls4_NativeRunnable
#define _Included_com_entis_android_entisgls4_NativeRunnable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_entis_android_entisgls4_NativeRunnable
 * Method:    nativeRun
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_entis_android_entisgls4_NativeRunnable_nativeRun
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
