

DECL_LOQUATY_FUNC(EntisGLS4_SceneInstancingItem_getBaseRotation);
DECL_LOQUATY_FUNC(EntisGLS4_SceneInstancingItem_setBaseRotation);
DECL_LOQUATY_FUNC(EntisGLS4_SceneInstancingItem_getBaseZoom);
DECL_LOQUATY_FUNC(EntisGLS4_SceneInstancingItem_setBaseZoom);
DECL_LOQUATY_FUNC(EntisGLS4_SceneInstancingItem_addTemporaryInstances);
DECL_LOQUATY_FUNC(EntisGLS4_SceneInstancingItem_getStaticInstanceCount);
DECL_LOQUATY_FUNC(EntisGLS4_SceneInstancingItem_getStaticInstanceAt);
DECL_LOQUATY_FUNC(EntisGLS4_SceneInstancingItem_insertStaticInstanceAt);
DECL_LOQUATY_FUNC(EntisGLS4_SceneInstancingItem_removeStaticInstanceAt);
DECL_LOQUATY_FUNC(EntisGLS4_SceneInstancingItem_lockInstancing);
DECL_LOQUATY_FUNC(EntisGLS4_SceneInstancingItem_unlockInstancing);


