

DECL_LOQUATY_CONSTRUCTOR(EntisGLS4_EditSprite);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_setEditStyle);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_getEditStyle);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_getCursorIndex);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_getSel);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_setSel);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_getSelText);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_getRangeText);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_canCopyText);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_canCutText);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_canPasteText);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_doClear);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_doCut);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_doCopy);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_doPaste);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_doReplace);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_canUndo);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_undo);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_canRedo);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_redo);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_doFindText);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_doFindTextFrom);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_getCharPosFromIndex);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_getLineFromIndex);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_getLineIndex);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_getLineLength);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_getLineCount);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_getLength);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_getLineText);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_getScrollPos_1);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_setScrollPos_1);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_getMaxLineWidth);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_getLineHeight);
DECL_LOQUATY_FUNC(EntisGLS4_EditSprite_scrollDeltaVertical);


