

DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_getLineVolume);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_setLineVolume);
DECL_LOQUATY_CONSTRUCTOR(EntisGLS4_AudioPlayer);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_open);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_create);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_clonePlayer);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_close);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_play);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_stop);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_setLoop);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_pause);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_restart);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_getVolume);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_setVolume);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_isPlaying);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_isPaused);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_getSampleFrequency);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_getTotalLength);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_getPosition);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_seekPosition);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_getAudioStream);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_releaseAudioStream);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_getVolumeLineMask);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_clearAllVolumeLines);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_setVolumeLineMask);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_setVolumeLine);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_resetVolumeLine);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_beginFadeVolume);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_isVolumeFading);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_cancelFadeVolume);
DECL_LOQUATY_FUNC(EntisGLS4_AudioPlayer_flushFadeVolume);


