

DECL_LOQUATY_FUNC(EntisGLS4_SceneParameter_colorFromVector);
DECL_LOQUATY_FUNC(EntisGLS4_SceneParameter_vectorFromColor);
DECL_LOQUATY_FUNC(EntisGLS4_SceneParameter_getMatrixParameter);
DECL_LOQUATY_FUNC(EntisGLS4_SceneParameter_getVectorParameter);
DECL_LOQUATY_FUNC(EntisGLS4_SceneParameter_getScalarParameter);
DECL_LOQUATY_FUNC(EntisGLS4_SceneParameter_getIntegerParameter);
DECL_LOQUATY_FUNC(EntisGLS4_SceneParameter_getBooleanParameter);
DECL_LOQUATY_FUNC(EntisGLS4_SceneParameter_getCommandParameter);
DECL_LOQUATY_FUNC(EntisGLS4_SceneParameter_getVector2dParameter);
DECL_LOQUATY_FUNC(EntisGLS4_SceneParameter_getVector4dParameter);
DECL_LOQUATY_FUNC(EntisGLS4_SceneParameter_getMatrix4dParameter);
DECL_LOQUATY_FUNC(EntisGLS4_SceneParameter_getBinaryParameter);
DECL_LOQUATY_FUNC(EntisGLS4_SceneParameter_setMatrixParameter);
DECL_LOQUATY_FUNC(EntisGLS4_SceneParameter_setVectorParameter);
DECL_LOQUATY_FUNC(EntisGLS4_SceneParameter_setScalarParameter);
DECL_LOQUATY_FUNC(EntisGLS4_SceneParameter_setIntegerParameter);
DECL_LOQUATY_FUNC(EntisGLS4_SceneParameter_setBooleanParameter);
DECL_LOQUATY_FUNC(EntisGLS4_SceneParameter_setCommandParameter);
DECL_LOQUATY_FUNC(EntisGLS4_SceneParameter_setVector2dParameter);
DECL_LOQUATY_FUNC(EntisGLS4_SceneParameter_setVector4dParameter);
DECL_LOQUATY_FUNC(EntisGLS4_SceneParameter_setMatrix4dParameter);
DECL_LOQUATY_FUNC(EntisGLS4_SceneParameter_setBinaryParameter);
DECL_LOQUATY_FUNC(EntisGLS4_SceneParameter_enumerateStringSet);


