

DECL_LOQUATY_FUNC(EntisGLS4_SpriteMouseListener_getButtonID);
DECL_LOQUATY_FUNC(EntisGLS4_SpriteMouseListener_getMouseID);
DECL_LOQUATY_FUNC(EntisGLS4_SpriteMouseListener_isFromTouch);
DECL_LOQUATY_CONSTRUCTOR(EntisGLS4_SpriteMouseListener);
DECL_LOQUATY_FUNC(EntisGLS4_SpriteMouseListener_getPointerCount);
DECL_LOQUATY_FUNC(EntisGLS4_SpriteMouseListener_findMouseIndexById);
DECL_LOQUATY_FUNC(EntisGLS4_SpriteMouseListener_getMousePointAt);
DECL_LOQUATY_FUNC(EntisGLS4_SpriteMouseListener_getMousePointAs);
DECL_LOQUATY_FUNC(EntisGLS4_SpriteMouseListener_isLButtonDownAt);
DECL_LOQUATY_FUNC(EntisGLS4_SpriteMouseListener_isRButtonDownAt);
DECL_LOQUATY_FUNC(EntisGLS4_SpriteMouseListener_getLDownPointsCount);
DECL_LOQUATY_FUNC(EntisGLS4_SpriteMouseListener_enumerateLDownPoints);


