

DECL_LOQUATY_CONSTRUCTOR(EntisGLS4_VertexBuffer);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_getBufferControlFlags);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_setBufferControlFlags);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_getDefaultMaterial);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_attachDefaultMaterial);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_allocatePrimitiveBuffer);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_addPrimitiveBuffer);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_freePrimitiveBuffer);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_getMeshCount);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_getMeshInfoAt);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_updateIndexedPrimitive);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_setExtendVertexAttribute);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_setBoneWeightMap);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_setBoneJointMap);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_allocateMorphing);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_setMorphingTargetMesh);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_setMorphingTargetWeight);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_createVariantBuffer);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_updateVertexVariant);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_newReferenceVariantBuffer);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_renderBufferTo);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_isModelIntoView);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_clearBuffer);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_releaseAllDeviceResources);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_setBufferUnitSize);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_getCircumscribedSphere);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_getCircumscribedParallelepiped);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_countOfTotalPolygons);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_countOfTotalVertices);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_enableMultiInstancingMode);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_isMultiInstancingMode);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_getInstancingCount);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_getInstancingEntries);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_clearAllInstance);
DECL_LOQUATY_FUNC(EntisGLS4_VertexBuffer_addInstanceVariant);


