

DECL_LOQUATY_FUNC(EntisGLS4_SceneProperty_getItemIdentity);
DECL_LOQUATY_FUNC(EntisGLS4_SceneProperty_setItemIdentity);
DECL_LOQUATY_FUNC(EntisGLS4_SceneProperty_getParameterCount);
DECL_LOQUATY_FUNC(EntisGLS4_SceneProperty_getParameterID);
DECL_LOQUATY_FUNC(EntisGLS4_SceneProperty_getParameterFriendlyName);
DECL_LOQUATY_FUNC(EntisGLS4_SceneProperty_getParameterDescription);
DECL_LOQUATY_FUNC(EntisGLS4_SceneProperty_findParameterID);
DECL_LOQUATY_FUNC(EntisGLS4_SceneProperty_getParameterType);
DECL_LOQUATY_FUNC(EntisGLS4_SceneProperty_getParameterAttributes);
DECL_LOQUATY_FUNC(EntisGLS4_SceneProperty_getParameterScalarRange);
DECL_LOQUATY_FUNC(EntisGLS4_SceneProperty_isParameterValidation);
DECL_LOQUATY_FUNC(EntisGLS4_SceneProperty_getParameterCategoryName);
DECL_LOQUATY_FUNC(EntisGLS4_SceneProperty_getParameterSequencer);
DECL_LOQUATY_FUNC(EntisGLS4_SceneProperty_createParameterSequencer);
DECL_LOQUATY_FUNC(EntisGLS4_SceneProperty_removeParameterSequencer);
DECL_LOQUATY_FUNC(EntisGLS4_SceneProperty_getPoseLibraryChain);


