

DECL_LOQUATY_CONSTRUCTOR(EntisGLS4_Collision);
DECL_LOQUATY_FUNC(EntisGLS4_Collision_getCurrentThickness);
DECL_LOQUATY_FUNC(EntisGLS4_Collision_setCurrentThickness);
DECL_LOQUATY_FUNC(EntisGLS4_Collision_attachMeshUserData);
DECL_LOQUATY_FUNC(EntisGLS4_Collision_getMeshUserData);
DECL_LOQUATY_FUNC(EntisGLS4_Collision_setSceneClassesMask);
DECL_LOQUATY_FUNC(EntisGLS4_Collision_getSceneClassesMask);
DECL_LOQUATY_FUNC(EntisGLS4_Collision_setUserClassesMask);
DECL_LOQUATY_FUNC(EntisGLS4_Collision_getUserClassesMask);
DECL_LOQUATY_FUNC(EntisGLS4_Collision_addSolidSphere);
DECL_LOQUATY_FUNC(EntisGLS4_Collision_addSolidCube);
DECL_LOQUATY_FUNC(EntisGLS4_Collision_addSolidTubeList);
DECL_LOQUATY_FUNC(EntisGLS4_Collision_addColliderObject);
DECL_LOQUATY_FUNC(EntisGLS4_Collision_beginBatchBuild);
DECL_LOQUATY_FUNC(EntisGLS4_Collision_endBatchBuild);


