

DECL_LOQUATY_CONSTRUCTOR(EntisGLS4_MovieSprite);
DECL_LOQUATY_FUNC(EntisGLS4_MovieSprite_openMovieFile);
DECL_LOQUATY_FUNC(EntisGLS4_MovieSprite_closeMovieFile);
DECL_LOQUATY_FUNC(EntisGLS4_MovieSprite_playMovie);
DECL_LOQUATY_FUNC(EntisGLS4_MovieSprite_stopMovie);
DECL_LOQUATY_FUNC(EntisGLS4_MovieSprite_setMovieLoop);
DECL_LOQUATY_FUNC(EntisGLS4_MovieSprite_isMovieLoop);
DECL_LOQUATY_FUNC(EntisGLS4_MovieSprite_pauseMovie);
DECL_LOQUATY_FUNC(EntisGLS4_MovieSprite_restartMovie);
DECL_LOQUATY_FUNC(EntisGLS4_MovieSprite_getVolume);
DECL_LOQUATY_FUNC(EntisGLS4_MovieSprite_setVolume);
DECL_LOQUATY_FUNC(EntisGLS4_MovieSprite_isMoviePlaying);
DECL_LOQUATY_FUNC(EntisGLS4_MovieSprite_isMoviePaused);
DECL_LOQUATY_FUNC(EntisGLS4_MovieSprite_getMovieFrequency);
DECL_LOQUATY_FUNC(EntisGLS4_MovieSprite_getMovieLength);
DECL_LOQUATY_FUNC(EntisGLS4_MovieSprite_getMoviePosition);
DECL_LOQUATY_FUNC(EntisGLS4_MovieSprite_seekMovie);
DECL_LOQUATY_FUNC(EntisGLS4_MovieSprite_getMovieSize);
DECL_LOQUATY_FUNC(EntisGLS4_MovieSprite_hasEndedOfDuration);
DECL_LOQUATY_FUNC(EntisGLS4_MovieSprite_resetEndOfDuration);


