

DECL_LOQUATY_CONSTRUCTOR(EntisGLS4_MaterialLibrary);
DECL_LOQUATY_FUNC(EntisGLS4_MaterialLibrary_loadLibraryXML);
DECL_LOQUATY_FUNC(EntisGLS4_MaterialLibrary_getMaterialAs);
DECL_LOQUATY_FUNC(EntisGLS4_MaterialLibrary_addMaterialAs);
DECL_LOQUATY_FUNC(EntisGLS4_MaterialLibrary_removeMaterialAs);
DECL_LOQUATY_FUNC(EntisGLS4_MaterialLibrary_removeAllMaterials);
DECL_LOQUATY_FUNC(EntisGLS4_MaterialLibrary_findMaterial);
DECL_LOQUATY_FUNC(EntisGLS4_MaterialLibrary_getMaterialCount);
DECL_LOQUATY_FUNC(EntisGLS4_MaterialLibrary_getMaterialIdentityAt);
DECL_LOQUATY_FUNC(EntisGLS4_MaterialLibrary_getMaterialIdentityOf);
DECL_LOQUATY_FUNC(EntisGLS4_MaterialLibrary_getMaterialAt);
DECL_LOQUATY_FUNC(EntisGLS4_MaterialLibrary_setParentLibrary);
DECL_LOQUATY_FUNC(EntisGLS4_MaterialLibrary_addReferenceLibrary);
DECL_LOQUATY_FUNC(EntisGLS4_MaterialLibrary_getParentLibrary);
DECL_LOQUATY_FUNC(EntisGLS4_MaterialLibrary_getReferenceLibraryCount);
DECL_LOQUATY_FUNC(EntisGLS4_MaterialLibrary_getReferenceLibraryAt);
DECL_LOQUATY_FUNC(EntisGLS4_MaterialLibrary_detachReferenceLibraryAt);
DECL_LOQUATY_FUNC(EntisGLS4_MaterialLibrary_detachReferenceLibraryOf);
DECL_LOQUATY_FUNC(EntisGLS4_MaterialLibrary_detachAllReferenceLibraries);


