

DECL_LOQUATY_FUNC(EntisGLS4_RenderBuffer_setShadingFlag);
DECL_LOQUATY_FUNC(EntisGLS4_RenderBuffer_getShadingFlag);
DECL_LOQUATY_FUNC(EntisGLS4_RenderBuffer_appendMatrixTransformation);
DECL_LOQUATY_FUNC(EntisGLS4_RenderBuffer_setMatrixTransformation);
DECL_LOQUATY_FUNC(EntisGLS4_RenderBuffer_pushTransformation);
DECL_LOQUATY_FUNC(EntisGLS4_RenderBuffer_popTransformation);
DECL_LOQUATY_FUNC(EntisGLS4_RenderBuffer_resetTransformation);
DECL_LOQUATY_FUNC(EntisGLS4_RenderBuffer_attachCustomShader);
DECL_LOQUATY_FUNC(EntisGLS4_RenderBuffer_getCustomShader);
DECL_LOQUATY_FUNC(EntisGLS4_RenderBuffer_setCustomShaderUniform);
DECL_LOQUATY_FUNC(EntisGLS4_RenderBuffer_setCustomShaderUniformImage);
DECL_LOQUATY_FUNC(EntisGLS4_RenderBuffer_resetCustomShaderUniform);
DECL_LOQUATY_FUNC(EntisGLS4_RenderBuffer_addIndexedPrimitive);
DECL_LOQUATY_FUNC(EntisGLS4_RenderBuffer_addVertexBuffer);
DECL_LOQUATY_FUNC(EntisGLS4_RenderBuffer_flush);
DECL_LOQUATY_FUNC(EntisGLS4_RenderBuffer_setOptionalFeature);
DECL_LOQUATY_FUNC(EntisGLS4_RenderBuffer_getOptionalFeature);


