

DECL_LOQUATY_CONSTRUCTOR(EntisGLS4_ModelPoseLibrary);
DECL_LOQUATY_FUNC(EntisGLS4_ModelPoseLibrary_loadLibrary);
DECL_LOQUATY_FUNC(EntisGLS4_ModelPoseLibrary_readLibrary);
DECL_LOQUATY_FUNC(EntisGLS4_ModelPoseLibrary_loadLibraryXML);
DECL_LOQUATY_FUNC(EntisGLS4_ModelPoseLibrary_saveLibrary);
DECL_LOQUATY_FUNC(EntisGLS4_ModelPoseLibrary_writeLibrary);
DECL_LOQUATY_FUNC(EntisGLS4_ModelPoseLibrary_saveLibraryXML);
DECL_LOQUATY_FUNC(EntisGLS4_ModelPoseLibrary_getPoseAs);
DECL_LOQUATY_FUNC(EntisGLS4_ModelPoseLibrary_getPoseAt);
DECL_LOQUATY_FUNC(EntisGLS4_ModelPoseLibrary_findPose);
DECL_LOQUATY_FUNC(EntisGLS4_ModelPoseLibrary_getPoseCount);
DECL_LOQUATY_FUNC(EntisGLS4_ModelPoseLibrary_getPoseIdentityAt);
DECL_LOQUATY_FUNC(EntisGLS4_ModelPoseLibrary_getPoseIdentityOf);
DECL_LOQUATY_FUNC(EntisGLS4_ModelPoseLibrary_addPoseAs);
DECL_LOQUATY_FUNC(EntisGLS4_ModelPoseLibrary_removePoseAs);
DECL_LOQUATY_FUNC(EntisGLS4_ModelPoseLibrary_removeAllPoses);
DECL_LOQUATY_FUNC(EntisGLS4_ModelPoseLibrary_setParentLibrary);
DECL_LOQUATY_FUNC(EntisGLS4_ModelPoseLibrary_addReferenceLibrary);
DECL_LOQUATY_FUNC(EntisGLS4_ModelPoseLibrary_getParentLibrary);
DECL_LOQUATY_FUNC(EntisGLS4_ModelPoseLibrary_getReferenceLibraryCount);
DECL_LOQUATY_FUNC(EntisGLS4_ModelPoseLibrary_getReferenceLibraryAt);
DECL_LOQUATY_FUNC(EntisGLS4_ModelPoseLibrary_detachReferenceLibraryAt);
DECL_LOQUATY_FUNC(EntisGLS4_ModelPoseLibrary_detachReferenceLibraryOf);
DECL_LOQUATY_FUNC(EntisGLS4_ModelPoseLibrary_detachAllReferenceLibraries);


