

DECL_LOQUATY_CONSTRUCTOR(EntisGLS4_ImageComposition);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_getCanvasSize);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_getImageMode);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_getChannelCount);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_setCanvasInfo);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_loadPSDFile);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_readPSDFile);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_savePSDFile);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_writePSDFile);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_getLayerCount);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_getLayerAt);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_getTreeLayerCount);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_getTreeLayerAt);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_insertLayerAt);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_appendLayer);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_localIndexToGlobal);
DECL_LOQUATY_FUNC(EntisGLS4_ImageComposition_removeLayer);


