

DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_getItemRotation);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_setItemRotation);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_getItemZoom);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_setItemZoom);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_getItemPosition);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_getItemTransparency);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_getItemColorEffect);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_getVisibleParameter);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_setVisibleParameter);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_setItemMatrix);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_setItemPositioin);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_getParentSpaceItem);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_getComposition);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_getComposer);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_getManager);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_getScene);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_getSceneItemAs);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_getItemLinkTransformation);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_getGlobalTransformation);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_getGlobalColorEffect);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_getChildItemCount);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_getChildItemAt);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_findChildItem);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_getControllerCount);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_findControllerID);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_findController);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_getControllerAt);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_getControllerAs);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_removeControllerAt);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_removeControllerAs);
DECL_LOQUATY_FUNC(EntisGLS4_SceneItem_isEditMode);


